/* Database schema to keep the structure of entire database. */

-- DROP TABLE animals;

/* Build 1.1 */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    PRIMARY KEY(id)
);

/* Build 1.2 */
ALTER TABLE animals
ADD COLUMN species varchar;

/* Build 1.3 */

CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(100),
    age INT,
    PRIMARY KEY(id)
);

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    PRIMARY KEY(id)
);

ALTER TABLE animals
DROP COLUMN species;

ALTER TABLE animals
ADD COLUMN species_id INT;

ALTER TABLE animals
    ADD CONSTRAINT fk_species
        FOREIGN KEY(species_id)
            REFERENCES species(id)

ALTER TABLE animals
ADD COLUMN owner_id INT;

ALTER TABLE animals
    ADD CONSTRAINT fk_owners
        FOREIGN KEY(owner_id)
            REFERENCES owners(id)

SELECT * FROM species;
