/* Database schema to keep the structure of entire database. */

DROP TABLE animals;

/* Build 1.1 */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    PRIMARY KEY(id)
);

/* Build 1.2 */
ALTER TABLE animals
ADD COLUMN species varchar;
