/* Database schema to keep the structure of entire database. */

DROP TABLE animals;

/* Build 1.1 */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    PRIMARY KEY(id)
);

/* Build 1.2 */
ALTER TABLE animals
ADD COLUMN species varchar;

BEGIN;
    UPDATE animals
    SET species = NULL;
COMMIT;

BEGIN;
    UPDATE animals
    SET species = 'Unspecified';
ROLLBACK;

BEGIN;
    UPDATE animals
    SET species = 'digimon'
    WHERE name LIKE '%mon';
COMMIT;

BEGIN;
    UPDATE animals
    SET species = 'pokemon'
    WHERE species IS NULL;
COMMIT;

BEGIN;
    DELETE FROM animals;
ROLLBACK;

UPDATE animals
SET weight_kg = weight_kg * (-1)
WHERE id = 1;

SELECT id,name,weight_kg from animals;

BEGIN;
    DELETE FROM animals
    WHERE date_of_birth > '2022-01-01';
    SAVEPOINT SP1;

    UPDATE animals
    SET weight_kg = weight_kg * -1;
    ROLLBACK TO SAVEPOINT SP1;

    UPDATE animals
    SET weight_kg = weight_kg * -1;
COMMIT;

SELECT id,name,weight_kg FROM animals;